// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/site.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for SiteService service

func NewSiteServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for SiteService service

type SiteService interface {
	GetImage(ctx context.Context, in *ImageReq, opts ...client.CallOption) (*ImageRes, error)
	GetSiteState(ctx context.Context, in *StateReq, opts ...client.CallOption) (*StateRes, error)
}

type siteService struct {
	c    client.Client
	name string
}

func NewSiteService(name string, c client.Client) SiteService {
	return &siteService{
		c:    c,
		name: name,
	}
}

func (c *siteService) GetImage(ctx context.Context, in *ImageReq, opts ...client.CallOption) (*ImageRes, error) {
	req := c.c.NewRequest(c.name, "SiteService.GetImage", in)
	out := new(ImageRes)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *siteService) GetSiteState(ctx context.Context, in *StateReq, opts ...client.CallOption) (*StateRes, error) {
	req := c.c.NewRequest(c.name, "SiteService.GetSiteState", in)
	out := new(StateRes)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for SiteService service

type SiteServiceHandler interface {
	GetImage(context.Context, *ImageReq, *ImageRes) error
	GetSiteState(context.Context, *StateReq, *StateRes) error
}

func RegisterSiteServiceHandler(s server.Server, hdlr SiteServiceHandler, opts ...server.HandlerOption) error {
	type siteService interface {
		GetImage(ctx context.Context, in *ImageReq, out *ImageRes) error
		GetSiteState(ctx context.Context, in *StateReq, out *StateRes) error
	}
	type SiteService struct {
		siteService
	}
	h := &siteServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&SiteService{h}, opts...))
}

type siteServiceHandler struct {
	SiteServiceHandler
}

func (h *siteServiceHandler) GetImage(ctx context.Context, in *ImageReq, out *ImageRes) error {
	return h.SiteServiceHandler.GetImage(ctx, in, out)
}

func (h *siteServiceHandler) GetSiteState(ctx context.Context, in *StateReq, out *StateRes) error {
	return h.SiteServiceHandler.GetSiteState(ctx, in, out)
}
