version: "3"

services: 
  auth:
    image: kira/auth
    container_name: auth
    environment: 
      - REGISTRY_ADDRESS=etcd:2379
    networks: 
      - kira

  gateway: 
    container_name: gateway
    image: kira/gateway
    links: 
      - file
      - user
      - auth
    networks: 
      - kira
    environment: 
      - MICRO_REGISTRY=etcd
      - MICRO_REGISTRY_ADDRESS=etcd:2379
      - MICRO_NAMESPACE=kira.micro.api
    ports: 
      - "3000:3000"

  file:
    image: kira/file
    container_name: file
    ports: 
      - "5001:5001"
    networks: 
      - kira
    environment: 
      - REGISTRY_ADDRESS=etcd:2379
      - MYSQL_ADDRESS=mysql:3306
      - API_ADDRESS=:5001
      - MINIO_ENDPOINT=minio:9000
  
  user:
    image: kira/user
    container_name: user
    links: 
      - auth
    ports: 
      - "5002:5002"
    networks:
      - kira
    environment: 
      - REGISTRY_ADDRESS=etcd:2379
      - MYSQL_ADDRESS=mysql:3306
      - API_ADDRESS=:5002


networks: 
  kira:
    external: 
      name: kira_net