version: "3"

services: 
  auth:
    image: kira/auth
    container_name: auth
    environment: 
      - REGISTRY_ADDRESS=etcd:2379
      - MYSQL_ADDRESS=mysql:3306
    networks: 
      - kira

  file:
    image: kira/file
    container_name: file
    expose: 
      - 5001
    networks: 
      - kira
    environment: 
      - REGISTRY_ADDRESS=etcd:2379
      - MYSQL_ADDRESS=mysql:3306
      - API_ADDRESS=:5001
      - MINIO_ENDPOINT=minio:9000
      - DOMAIN=api.test.me
      - REDIS_ADDRESS=redis:6379
      - NATS_ADDRESS=nats://nats:4222
    labels: 
      - traefik.enable=true
      - traefik.http.routers.file.rule=Host(`api.test.me`) && (PathPrefix(`/v1/file`) || PathPrefix(`/file`))
      - traefik.http.services.file.loadbalancer.server.port=5001

  
  user:
    image: kira/user
    container_name: user
    links: 
      - auth
    expose: 
      - 5002
    networks:
      - kira
    environment: 
      - REGISTRY_ADDRESS=etcd:2379
      - MYSQL_ADDRESS=mysql:3306
      - API_ADDRESS=:5002
      - REDIS_ADDRESS=redis:6379
      - NATS_ADDRESS=nats://nats:4222

    labels: 
      - traefik.enable=true
      - traefik.http.routers.user.rule=Host(`api.test.me`) && PathPrefix(`/v1/user`)
      - traefik.http.services.user.loadbalancer.server.port=5002
  
  site:
    image: kira/site
    container_name: site
    expose: 
      - 5000
    networks:
      - kira
    environment: 
      - API_ADDRESS=:5000
      - REDIS_ADDRESS=redis:6379
      - REGISTRY_ADDRESS=etcd:2379
    labels: 
      - traefik.enable=true
      - traefik.http.routers.site.rule=(Host(`api.test.me`) && PathPrefix(`/v1/site`)) || Host(`img.test.me`)
      - traefik.http.services.site.loadbalancer.server.port=5000
  
  upload:
    image: kira/upload
    container_name: upload
    expose: 
      - 5003
    networks: 
      - kira
    environment: 
      - REGISTRY_ADDRESS=etcd:2379
      - MYSQL_ADDRESS=mysql:3306
      - API_ADDRESS=:5003
      - MINIO_ENDPOINT=minio:9000
      - REDIS_ADDRESS=redis:6379
      - GIN_MODE=release
    labels: 
      - traefik.enable=true
      - traefik.http.routers.upload.rule=Host(`api.test.me`) && PathPrefix(`/v1/upload`)
      - traefik.http.services.upload.loadbalancer.server.port=5003

networks: 
  kira:
    external: 
      name: kira_net