version: "3"

services: 
  auth:
    image: kira/auth
    container_name: auth
    environment: 
      - REGISTRY_ADDRESS=etcd:2379
    networks: 
      - kira

  file:
    image: kira/file
    container_name: file
    expose: 
      - 5001
    networks: 
      - kira
    environment: 
      - REGISTRY_ADDRESS=etcd:2379
      - MYSQL_ADDRESS=mysql:3306
      - API_ADDRESS=:5001
      - MINIO_ENDPOINT=minio:9000
      - DOMAIN=api.test.me
    labels: 
      - traefik.enable=true
      - traefik.http.routers.file.rule=Host(`api.test.me`) && (PathPrefix(`/v1/file`) || PathPrefix(`/file`))
      - traefik.http.services.file.loadbalancer.server.port=5001

  
  user:
    image: kira/user
    container_name: user
    links: 
      - auth
    expose: 
      - 5002
    networks:
      - kira
    environment: 
      - REGISTRY_ADDRESS=etcd:2379
      - MYSQL_ADDRESS=mysql:3306
      - API_ADDRESS=:5002
    labels: 
      - traefik.enable=true
      - traefik.http.routers.user.rule=Host(`api.test.me`) && PathPrefix(`/v1/user`)
      - traefik.http.services.user.loadbalancer.server.port=5002


networks: 
  kira:
    external: 
      name: kira_net