// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/auth.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for AuthService service

func NewAuthServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for AuthService service

type AuthService interface {
	Auth(ctx context.Context, in *AuthRequest, opts ...client.CallOption) (*AuthResponse, error)
	Valid(ctx context.Context, in *TokenRequest, opts ...client.CallOption) (*ValidResponse, error)
	Refresh(ctx context.Context, in *TokenRequest, opts ...client.CallOption) (*AuthResponse, error)
	FileToken(ctx context.Context, in *FileTokenRequest, opts ...client.CallOption) (*FileTokenResponse, error)
	Ping(ctx context.Context, in *Ping, opts ...client.CallOption) (*Pong, error)
}

type authService struct {
	c    client.Client
	name string
}

func NewAuthService(name string, c client.Client) AuthService {
	return &authService{
		c:    c,
		name: name,
	}
}

func (c *authService) Auth(ctx context.Context, in *AuthRequest, opts ...client.CallOption) (*AuthResponse, error) {
	req := c.c.NewRequest(c.name, "AuthService.Auth", in)
	out := new(AuthResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authService) Valid(ctx context.Context, in *TokenRequest, opts ...client.CallOption) (*ValidResponse, error) {
	req := c.c.NewRequest(c.name, "AuthService.Valid", in)
	out := new(ValidResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authService) Refresh(ctx context.Context, in *TokenRequest, opts ...client.CallOption) (*AuthResponse, error) {
	req := c.c.NewRequest(c.name, "AuthService.Refresh", in)
	out := new(AuthResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authService) FileToken(ctx context.Context, in *FileTokenRequest, opts ...client.CallOption) (*FileTokenResponse, error) {
	req := c.c.NewRequest(c.name, "AuthService.FileToken", in)
	out := new(FileTokenResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authService) Ping(ctx context.Context, in *Ping, opts ...client.CallOption) (*Pong, error) {
	req := c.c.NewRequest(c.name, "AuthService.Ping", in)
	out := new(Pong)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for AuthService service

type AuthServiceHandler interface {
	Auth(context.Context, *AuthRequest, *AuthResponse) error
	Valid(context.Context, *TokenRequest, *ValidResponse) error
	Refresh(context.Context, *TokenRequest, *AuthResponse) error
	FileToken(context.Context, *FileTokenRequest, *FileTokenResponse) error
	Ping(context.Context, *Ping, *Pong) error
}

func RegisterAuthServiceHandler(s server.Server, hdlr AuthServiceHandler, opts ...server.HandlerOption) error {
	type authService interface {
		Auth(ctx context.Context, in *AuthRequest, out *AuthResponse) error
		Valid(ctx context.Context, in *TokenRequest, out *ValidResponse) error
		Refresh(ctx context.Context, in *TokenRequest, out *AuthResponse) error
		FileToken(ctx context.Context, in *FileTokenRequest, out *FileTokenResponse) error
		Ping(ctx context.Context, in *Ping, out *Pong) error
	}
	type AuthService struct {
		authService
	}
	h := &authServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&AuthService{h}, opts...))
}

type authServiceHandler struct {
	AuthServiceHandler
}

func (h *authServiceHandler) Auth(ctx context.Context, in *AuthRequest, out *AuthResponse) error {
	return h.AuthServiceHandler.Auth(ctx, in, out)
}

func (h *authServiceHandler) Valid(ctx context.Context, in *TokenRequest, out *ValidResponse) error {
	return h.AuthServiceHandler.Valid(ctx, in, out)
}

func (h *authServiceHandler) Refresh(ctx context.Context, in *TokenRequest, out *AuthResponse) error {
	return h.AuthServiceHandler.Refresh(ctx, in, out)
}

func (h *authServiceHandler) FileToken(ctx context.Context, in *FileTokenRequest, out *FileTokenResponse) error {
	return h.AuthServiceHandler.FileToken(ctx, in, out)
}

func (h *authServiceHandler) Ping(ctx context.Context, in *Ping, out *Pong) error {
	return h.AuthServiceHandler.Ping(ctx, in, out)
}
