// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/file.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for FileService service

func NewFileServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for FileService service

type FileService interface {
	// RPC
	GenerateToken(ctx context.Context, in *TokenUserReq, opts ...client.CallOption) (*TokenUserRes, error)
	GetImage(ctx context.Context, in *GetImageReq, opts ...client.CallOption) (*GetImageRes, error)
	GetUserImages(ctx context.Context, in *GetUserImagesReq, opts ...client.CallOption) (*GetUserImagesRes, error)
	ChangeTokenStatus(ctx context.Context, in *ChangeTokenStatusReq, opts ...client.CallOption) (*ChangeTokenStatusRes, error)
	CheckTokenStatus(ctx context.Context, in *CheckTokenStatusReq, opts ...client.CallOption) (*CheckTokenStatusRes, error)
	GetAnonyFiles(ctx context.Context, in *GetAnonyFilesReq, opts ...client.CallOption) (*GetAnonyFilesRes, error)
	DeleteAnonyFile(ctx context.Context, in *DeleteAnonyReq, opts ...client.CallOption) (*DeleteAnonyRes, error)
	Ping(ctx context.Context, in *Ping, opts ...client.CallOption) (*Pong, error)
	// API
	GetHistory(ctx context.Context, in *GetHistoryReq, opts ...client.CallOption) (*GetHistoryRes, error)
	DeleteFile(ctx context.Context, in *DeleteFileReq, opts ...client.CallOption) (*DeleteFileRes, error)
	GetDetail(ctx context.Context, in *GetDetailReq, opts ...client.CallOption) (*GetDetailRes, error)
	RefreshToken(ctx context.Context, in *TokenReq, opts ...client.CallOption) (*TokenUserRes, error)
	GetRandomFile(ctx context.Context, in *TokenReq, opts ...client.CallOption) (*RandomFiles, error)
	GetHotLikeRank(ctx context.Context, in *TokenReq, opts ...client.CallOption) (*HotLikeRankList, error)
	// User
	GetToken(ctx context.Context, in *TokenUserReq, opts ...client.CallOption) (*TokenUserRes, error)
	LikeOrDislike(ctx context.Context, in *FileLikeReq, opts ...client.CallOption) (*Response, error)
	GetLikes(ctx context.Context, in *GetLikesReq, opts ...client.CallOption) (*GetLikesRes, error)
	DeleteUserFile(ctx context.Context, in *DeleteUserFileReq, opts ...client.CallOption) (*DeleteUserFileRes, error)
}

type fileService struct {
	c    client.Client
	name string
}

func NewFileService(name string, c client.Client) FileService {
	return &fileService{
		c:    c,
		name: name,
	}
}

func (c *fileService) GenerateToken(ctx context.Context, in *TokenUserReq, opts ...client.CallOption) (*TokenUserRes, error) {
	req := c.c.NewRequest(c.name, "FileService.GenerateToken", in)
	out := new(TokenUserRes)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileService) GetImage(ctx context.Context, in *GetImageReq, opts ...client.CallOption) (*GetImageRes, error) {
	req := c.c.NewRequest(c.name, "FileService.GetImage", in)
	out := new(GetImageRes)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileService) GetUserImages(ctx context.Context, in *GetUserImagesReq, opts ...client.CallOption) (*GetUserImagesRes, error) {
	req := c.c.NewRequest(c.name, "FileService.GetUserImages", in)
	out := new(GetUserImagesRes)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileService) ChangeTokenStatus(ctx context.Context, in *ChangeTokenStatusReq, opts ...client.CallOption) (*ChangeTokenStatusRes, error) {
	req := c.c.NewRequest(c.name, "FileService.ChangeTokenStatus", in)
	out := new(ChangeTokenStatusRes)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileService) CheckTokenStatus(ctx context.Context, in *CheckTokenStatusReq, opts ...client.CallOption) (*CheckTokenStatusRes, error) {
	req := c.c.NewRequest(c.name, "FileService.CheckTokenStatus", in)
	out := new(CheckTokenStatusRes)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileService) GetAnonyFiles(ctx context.Context, in *GetAnonyFilesReq, opts ...client.CallOption) (*GetAnonyFilesRes, error) {
	req := c.c.NewRequest(c.name, "FileService.GetAnonyFiles", in)
	out := new(GetAnonyFilesRes)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileService) DeleteAnonyFile(ctx context.Context, in *DeleteAnonyReq, opts ...client.CallOption) (*DeleteAnonyRes, error) {
	req := c.c.NewRequest(c.name, "FileService.DeleteAnonyFile", in)
	out := new(DeleteAnonyRes)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileService) Ping(ctx context.Context, in *Ping, opts ...client.CallOption) (*Pong, error) {
	req := c.c.NewRequest(c.name, "FileService.Ping", in)
	out := new(Pong)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileService) GetHistory(ctx context.Context, in *GetHistoryReq, opts ...client.CallOption) (*GetHistoryRes, error) {
	req := c.c.NewRequest(c.name, "FileService.GetHistory", in)
	out := new(GetHistoryRes)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileService) DeleteFile(ctx context.Context, in *DeleteFileReq, opts ...client.CallOption) (*DeleteFileRes, error) {
	req := c.c.NewRequest(c.name, "FileService.DeleteFile", in)
	out := new(DeleteFileRes)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileService) GetDetail(ctx context.Context, in *GetDetailReq, opts ...client.CallOption) (*GetDetailRes, error) {
	req := c.c.NewRequest(c.name, "FileService.GetDetail", in)
	out := new(GetDetailRes)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileService) RefreshToken(ctx context.Context, in *TokenReq, opts ...client.CallOption) (*TokenUserRes, error) {
	req := c.c.NewRequest(c.name, "FileService.RefreshToken", in)
	out := new(TokenUserRes)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileService) GetRandomFile(ctx context.Context, in *TokenReq, opts ...client.CallOption) (*RandomFiles, error) {
	req := c.c.NewRequest(c.name, "FileService.GetRandomFile", in)
	out := new(RandomFiles)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileService) GetHotLikeRank(ctx context.Context, in *TokenReq, opts ...client.CallOption) (*HotLikeRankList, error) {
	req := c.c.NewRequest(c.name, "FileService.GetHotLikeRank", in)
	out := new(HotLikeRankList)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileService) GetToken(ctx context.Context, in *TokenUserReq, opts ...client.CallOption) (*TokenUserRes, error) {
	req := c.c.NewRequest(c.name, "FileService.GetToken", in)
	out := new(TokenUserRes)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileService) LikeOrDislike(ctx context.Context, in *FileLikeReq, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "FileService.LikeOrDislike", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileService) GetLikes(ctx context.Context, in *GetLikesReq, opts ...client.CallOption) (*GetLikesRes, error) {
	req := c.c.NewRequest(c.name, "FileService.GetLikes", in)
	out := new(GetLikesRes)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileService) DeleteUserFile(ctx context.Context, in *DeleteUserFileReq, opts ...client.CallOption) (*DeleteUserFileRes, error) {
	req := c.c.NewRequest(c.name, "FileService.DeleteUserFile", in)
	out := new(DeleteUserFileRes)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for FileService service

type FileServiceHandler interface {
	// RPC
	GenerateToken(context.Context, *TokenUserReq, *TokenUserRes) error
	GetImage(context.Context, *GetImageReq, *GetImageRes) error
	GetUserImages(context.Context, *GetUserImagesReq, *GetUserImagesRes) error
	ChangeTokenStatus(context.Context, *ChangeTokenStatusReq, *ChangeTokenStatusRes) error
	CheckTokenStatus(context.Context, *CheckTokenStatusReq, *CheckTokenStatusRes) error
	GetAnonyFiles(context.Context, *GetAnonyFilesReq, *GetAnonyFilesRes) error
	DeleteAnonyFile(context.Context, *DeleteAnonyReq, *DeleteAnonyRes) error
	Ping(context.Context, *Ping, *Pong) error
	// API
	GetHistory(context.Context, *GetHistoryReq, *GetHistoryRes) error
	DeleteFile(context.Context, *DeleteFileReq, *DeleteFileRes) error
	GetDetail(context.Context, *GetDetailReq, *GetDetailRes) error
	RefreshToken(context.Context, *TokenReq, *TokenUserRes) error
	GetRandomFile(context.Context, *TokenReq, *RandomFiles) error
	GetHotLikeRank(context.Context, *TokenReq, *HotLikeRankList) error
	// User
	GetToken(context.Context, *TokenUserReq, *TokenUserRes) error
	LikeOrDislike(context.Context, *FileLikeReq, *Response) error
	GetLikes(context.Context, *GetLikesReq, *GetLikesRes) error
	DeleteUserFile(context.Context, *DeleteUserFileReq, *DeleteUserFileRes) error
}

func RegisterFileServiceHandler(s server.Server, hdlr FileServiceHandler, opts ...server.HandlerOption) error {
	type fileService interface {
		GenerateToken(ctx context.Context, in *TokenUserReq, out *TokenUserRes) error
		GetImage(ctx context.Context, in *GetImageReq, out *GetImageRes) error
		GetUserImages(ctx context.Context, in *GetUserImagesReq, out *GetUserImagesRes) error
		ChangeTokenStatus(ctx context.Context, in *ChangeTokenStatusReq, out *ChangeTokenStatusRes) error
		CheckTokenStatus(ctx context.Context, in *CheckTokenStatusReq, out *CheckTokenStatusRes) error
		GetAnonyFiles(ctx context.Context, in *GetAnonyFilesReq, out *GetAnonyFilesRes) error
		DeleteAnonyFile(ctx context.Context, in *DeleteAnonyReq, out *DeleteAnonyRes) error
		Ping(ctx context.Context, in *Ping, out *Pong) error
		GetHistory(ctx context.Context, in *GetHistoryReq, out *GetHistoryRes) error
		DeleteFile(ctx context.Context, in *DeleteFileReq, out *DeleteFileRes) error
		GetDetail(ctx context.Context, in *GetDetailReq, out *GetDetailRes) error
		RefreshToken(ctx context.Context, in *TokenReq, out *TokenUserRes) error
		GetRandomFile(ctx context.Context, in *TokenReq, out *RandomFiles) error
		GetHotLikeRank(ctx context.Context, in *TokenReq, out *HotLikeRankList) error
		GetToken(ctx context.Context, in *TokenUserReq, out *TokenUserRes) error
		LikeOrDislike(ctx context.Context, in *FileLikeReq, out *Response) error
		GetLikes(ctx context.Context, in *GetLikesReq, out *GetLikesRes) error
		DeleteUserFile(ctx context.Context, in *DeleteUserFileReq, out *DeleteUserFileRes) error
	}
	type FileService struct {
		fileService
	}
	h := &fileServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&FileService{h}, opts...))
}

type fileServiceHandler struct {
	FileServiceHandler
}

func (h *fileServiceHandler) GenerateToken(ctx context.Context, in *TokenUserReq, out *TokenUserRes) error {
	return h.FileServiceHandler.GenerateToken(ctx, in, out)
}

func (h *fileServiceHandler) GetImage(ctx context.Context, in *GetImageReq, out *GetImageRes) error {
	return h.FileServiceHandler.GetImage(ctx, in, out)
}

func (h *fileServiceHandler) GetUserImages(ctx context.Context, in *GetUserImagesReq, out *GetUserImagesRes) error {
	return h.FileServiceHandler.GetUserImages(ctx, in, out)
}

func (h *fileServiceHandler) ChangeTokenStatus(ctx context.Context, in *ChangeTokenStatusReq, out *ChangeTokenStatusRes) error {
	return h.FileServiceHandler.ChangeTokenStatus(ctx, in, out)
}

func (h *fileServiceHandler) CheckTokenStatus(ctx context.Context, in *CheckTokenStatusReq, out *CheckTokenStatusRes) error {
	return h.FileServiceHandler.CheckTokenStatus(ctx, in, out)
}

func (h *fileServiceHandler) GetAnonyFiles(ctx context.Context, in *GetAnonyFilesReq, out *GetAnonyFilesRes) error {
	return h.FileServiceHandler.GetAnonyFiles(ctx, in, out)
}

func (h *fileServiceHandler) DeleteAnonyFile(ctx context.Context, in *DeleteAnonyReq, out *DeleteAnonyRes) error {
	return h.FileServiceHandler.DeleteAnonyFile(ctx, in, out)
}

func (h *fileServiceHandler) Ping(ctx context.Context, in *Ping, out *Pong) error {
	return h.FileServiceHandler.Ping(ctx, in, out)
}

func (h *fileServiceHandler) GetHistory(ctx context.Context, in *GetHistoryReq, out *GetHistoryRes) error {
	return h.FileServiceHandler.GetHistory(ctx, in, out)
}

func (h *fileServiceHandler) DeleteFile(ctx context.Context, in *DeleteFileReq, out *DeleteFileRes) error {
	return h.FileServiceHandler.DeleteFile(ctx, in, out)
}

func (h *fileServiceHandler) GetDetail(ctx context.Context, in *GetDetailReq, out *GetDetailRes) error {
	return h.FileServiceHandler.GetDetail(ctx, in, out)
}

func (h *fileServiceHandler) RefreshToken(ctx context.Context, in *TokenReq, out *TokenUserRes) error {
	return h.FileServiceHandler.RefreshToken(ctx, in, out)
}

func (h *fileServiceHandler) GetRandomFile(ctx context.Context, in *TokenReq, out *RandomFiles) error {
	return h.FileServiceHandler.GetRandomFile(ctx, in, out)
}

func (h *fileServiceHandler) GetHotLikeRank(ctx context.Context, in *TokenReq, out *HotLikeRankList) error {
	return h.FileServiceHandler.GetHotLikeRank(ctx, in, out)
}

func (h *fileServiceHandler) GetToken(ctx context.Context, in *TokenUserReq, out *TokenUserRes) error {
	return h.FileServiceHandler.GetToken(ctx, in, out)
}

func (h *fileServiceHandler) LikeOrDislike(ctx context.Context, in *FileLikeReq, out *Response) error {
	return h.FileServiceHandler.LikeOrDislike(ctx, in, out)
}

func (h *fileServiceHandler) GetLikes(ctx context.Context, in *GetLikesReq, out *GetLikesRes) error {
	return h.FileServiceHandler.GetLikes(ctx, in, out)
}

func (h *fileServiceHandler) DeleteUserFile(ctx context.Context, in *DeleteUserFileReq, out *DeleteUserFileRes) error {
	return h.FileServiceHandler.DeleteUserFile(ctx, in, out)
}
