skinparam DefaultFontName ttf-wqy-zenhei
@startuml 系统用例图
left to right direction
actor "匿名用户" as anony
actor "注册用户" as user
actor "管理员" as admin

package Server {
    usecase "上传文件" as Upload
    usecase "获取随机图片" as Random
    usecase "获取用户图片" as User
    usecase "注册" as Signup
    usecase "登录" as Signin
    usecase "获取上传历史" as History
    usecase "删除图片" as Delete
    usecase "点赞或取消点赞图片" as LikeOrDislike
    usecase "获取点赞列表" as LikeList
    usecase "更改密码" as ChangePassword
    usecase "更新图片令牌" as ChangeToken
    usecase "获取用户列表" as UserList
    usecase "获取用户上传列表" as FileList
    usecase "更改用户状态" as ChangeUserStatus
    usecase "删除用户上传图片" as DeleteFile
    usecase "删除用户账号" as DeleteAccount
}

anony --> Upload
anony --> Random
anony --> User
anony --> Signup
anony --> Signin

anony <|-- user

user --> History
user --> Delete
user --> LikeOrDislike 
user --> LikeList
user --> ChangePassword
user --> ChangeToken

FileList <-- admin
ChangeUserStatus <-- admin
DeleteFile <-- admin 
DeleteAccount <-- admin
Signin <-- admin
UserList <-- admin

@enduml