version: "3"

services: 
  auth:
    image: kira/auth
    container_name: auth
    environment: 
      - REGISTRY_ADDRESS=etcd:2379
      - JAEGER_ADDRESS=jaeger:6831
      - MYSQL_ADDRESS=mysql:3306
    networks: 
      - kira

  file:
    image: kira/file
    container_name: file
    networks: 
      - kira
    environment: 
      - REGISTRY_ADDRESS=etcd:2379
      - MYSQL_ADDRESS=mysql:3306
      - API_ADDRESS=:5001
      - MINIO_ENDPOINT=172.19.0.1:9000
      - MINIO_ACCESSKEY=minio
      - MINIO_SECRETKEY=minio123
      - GIN_MODE=release
      - DOMAIN=api.test.me
      - REDIS_ADDRESS=redis:6379
      - NATS_ADDRESS=nats://nats:4222
      - JAEGER_ADDRESS=jaeger:6831

  file-api:
    image: kira/file-api
    container_name: file-api
    # ports: 
    #   - "5001:5001"
    networks: 
      - kira
    environment: 
      - REGISTRY_ADDRESS=etcd:2379
      - GIN_MODE=release
      - JAEGER_ADDRESS=jaeger:6831
      - REDIS_ADDRESS=redis:6379
      - MYSQL_ADDRESS=mysql:3306
    labels: 
      - "traefik.enable=true"
      - "traefik.http.routers.file.rule=PathPrefix(`/file`)"
      - "traefik.http.services.file.loadbalancer.server.port=5001"

  user:
    image: kira/user
    container_name: user
    networks:
      - kira
    environment: 
      - REGISTRY_ADDRESS=etcd:2379
      - MYSQL_ADDRESS=mysql:3306
      - REDIS_ADDRESS=redis:6379
      - JAEGER_ADDRESS=jaeger:6831
      - NATS_ADDRESS=nats://nats:4222

  user-api:
    image: kira/user-api
    container_name: user-api
    # ports: 
    #   - "5002:5002"
    networks:
      - kira
    environment: 
      - REGISTRY_ADDRESS=etcd:2379
      - API_ADDRESS=:5002
      - JAEGER_ADDRESS=jaeger:6831
      - REDIS_ADDRESS=redis:6379
      - GIN_MODE=release
      - MYSQL_ADDRESS=mysql:3306
    labels: 
      - "traefik.enable=true"
      - "traefik.http.routers.user.rule=PathPrefix(`/user`)"
      - "traefik.http.services.user.loadbalancer.server.port=5002"
      
  site:
    image: kira/site
    container_name: site
    # ports: 
    #   - "5000:5000"
    networks:
      - kira
    environment: 
      - API_ADDRESS=:5000
      - REDIS_ADDRESS=redis:6379
      - REGISTRY_ADDRESS=etcd:2379
      - JAEGER_ADDRESS=jaeger:6831
      - GIN_MODE=release
    labels: 
      - "traefik.enable=true"
      - "traefik.http.routers.site.rule=PathPrefix(`/site`) || PathPrefix(`/image`) || PathPrefix(`/download`)"
      - "traefik.http.services.site.loadbalancer.server.port=5000"
  
  upload:
    image: kira/upload
    container_name: upload
    networks: 
      - kira
    environment: 
      - REGISTRY_ADDRESS=etcd:2379
      - MYSQL_ADDRESS=mysql:3306
      - MINIO_ENDPOINT=172.19.0.1:9000
      - MINIO_ACCESSKEY=minio
      - MINIO_SECRETKEY=minio123
      - REDIS_ADDRESS=redis:6379
      - JAEGER_ADDRESS=jaeger:6831
      - GIN_MODE=release
      - DOMAIN=api.test.me
 
  upload-api:
    image: kira/upload-api
    container_name: upload-api
    # ports: 
    #   - "5003:5003"
    networks: 
      - kira
    environment: 
      - REGISTRY_ADDRESS=etcd:2379
      - API_ADDRESS=:5003
      - JAEGER_ADDRESS=jaeger:6831
      - GIN_MODE=release
      - REDIS_ADDRESS=redis:6379
    labels: 
      - "traefik.enable=true"
      - "traefik.http.routers.upload.rule=PathPrefix(`/upload`)"
      - "traefik.http.services.upload.loadbalancer.server.port=5003"
  
  # gateway:
  #   image: kira/gateway
  #   container_name: gateway
  #   ports:
  #     - "8080:8080"
  #   networks:
  #     - kira
  #   environment:
  #     - MICRO_REGISTRY=etcd
  #     - MICRO_REGISTRY_ADDRESS=etcd:2379
  #     - MICRO_API_HANDLER=http
  #   labels: 
  #     - traefik.enable=true
  #     - traefik.http.routers.gateway.rule=Host(`test.me`) || Host(`192.168.186.128`) || Host(`kira.zxykm.ltd`)
  #     - traefik.http.services.gateway.loadbalancer.server.port=8080

networks: 
  kira:
    external: 
      name: kira_net
