version: "3"

services: 
  auth:
    image: kira/auth
    container_name: auth
    environment: 
      - REGISTRY_ADDRESS=etcd:2379
      - JAEGER_ADDRESS=jaeger:6831
      - MYSQL_ADDRESS=mysql:3306
    networks: 
      - kira

  file:
    image: kira/file
    container_name: file
    # ports: 
    #   - "5001:5001"
    networks: 
      - kira
    environment: 
      - REGISTRY_ADDRESS=etcd:2379
      - MYSQL_ADDRESS=mysql:3306
      - API_ADDRESS=:5001
      - MINIO_ENDPOINT=minio:9000
      - DOMAIN=api.test.me
      - REDIS_ADDRESS=redis:6379
      - NATS_ADDRESS=nats://nats:4222
      # - GIN_MODE=release
      - JAEGER_ADDRESS=jaeger:6831
    # labels: 
    #   - traefik.enable=true
    #   - traefik.http.routers.file.rule=(PathPrefix(`/v1/file`) || PathPrefix(`/file`))
    #   - traefik.http.services.file.loadbalancer.server.port=5001

  file-api:
    image: kira/file-api
    container_name: file-api
    ports: 
      - "5001:5001"
    networks: 
      - kira
    environment: 
      - REGISTRY_ADDRESS=etcd:2379
      - GIN_MODE=release
      - JAEGER_ADDRESS=jaeger:6831
      - REDIS_ADDRESS=redis:6379

    labels: 
      - traefik.enable=true
      - traefik.http.routers.file.rule=(PathPrefix(`/v1/file`) || PathPrefix(`/file`))
      - traefik.http.services.file.loadbalancer.server.port=5001

  
  user:
    image: kira/user
    container_name: user
    links: 
      - auth
    # ports: 
    #   - "5002:5002"
    networks:
      - kira
    environment: 
      - REGISTRY_ADDRESS=etcd:2379
      - MYSQL_ADDRESS=mysql:3306
      # - API_ADDRESS=:5002
      - REDIS_ADDRESS=redis:6379
      - JAEGER_ADDRESS=jaeger:6831
      - NATS_ADDRESS=nats://nats:4222
    # labels: 
    #   - traefik.enable=true
    #   - traefik.http.routers.user.rule=PathPrefix(`/v1/user`)
    #   - traefik.http.services.user.loadbalancer.server.port=5002

  user-api:
    image: kira/user-api
    container_name: user-api
    links: 
      - auth
    ports: 
      - "5002:5002"
    volumes: 
      - $HOME/workspace/kira-project/kira/deploy/bin/casbin:/casbin
    networks:
      - kira
    environment: 
      - REGISTRY_ADDRESS=etcd:2379
      - API_ADDRESS=:5002
      - JAEGER_ADDRESS=jaeger:6831
      - REDIS_ADDRESS=redis:6379
    labels: 
      - traefik.enable=true
      - traefik.http.routers.user.rule=PathPrefix(`/v1/user`)
      - traefik.http.services.user.loadbalancer.server.port=5002
  
  site:
    image: kira/site
    container_name: site
    ports: 
      - "5000:5000"
    networks:
      - kira
    environment: 
      - API_ADDRESS=:5000
      - REDIS_ADDRESS=redis:6379
      - REGISTRY_ADDRESS=etcd:2379
      - JAEGER_ADDRESS=jaeger:6831
    labels: 
      - traefik.enable=true
      - traefik.http.routers.site.rule=PathPrefix(`/v1/site`) || PathPrefix(`/image`)
      - traefik.http.services.site.loadbalancer.server.port=5000
  
  upload:
    image: kira/upload
    container_name: upload
    networks: 
      - kira
    environment: 
      - REGISTRY_ADDRESS=etcd:2379
      - MYSQL_ADDRESS=mysql:3306
      - MINIO_ENDPOINT=minio:9000
      - REDIS_ADDRESS=redis:6379
      - JAEGER_ADDRESS=jaeger:6831
    # labels: 
    #   - traefik.enable=true
    #   - traefik.http.routers.upload.rule=PathPrefix(`/v1/upload`)
    #   - traefik.http.services.upload.loadbalancer.server.port=5003
  
  upload-api:
    image: kira/upload-api
    container_name: upload-api
    ports: 
      - "5003:5003"
    networks: 
      - kira
    environment: 
      - REGISTRY_ADDRESS=etcd:2379
      - API_ADDRESS=:5003
      - JAEGER_ADDRESS=jaeger:6831
      - GIN_MODE=release
      - REDIS_ADDRESS=redis:6379
    labels: 
      - traefik.enable=true
      - traefik.http.routers.upload.rule=PathPrefix(`/v1/upload`)
      - traefik.http.services.upload.loadbalancer.server.port=5003

networks: 
  kira:
    external: 
      name: kira_net
